Data Source=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=10.69.4.246)(PORT=1521)))(CONNECT_DATA=(SID=th)));User Id=area2;Password=cuuwfxmgdgdldi2;

SELECT * 
FROM BARCODEREADS 
ORDER BY TIMESTAMP DESC